[package]
name = "ggez_specs"
version = "0.1.0"
authors = ["Mark Horvath <mark.horvath@vodafone.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
specs = "0.15.0"
specs-derive = "0.4.0"
